routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function (){

    Auth::routes();

    Route::group(['middleware' => ['auth','privileges']], function (){
        Route::get('getCitiesAjaxList/{country}/{city?}', 'Controller@getCitiesAjaxList')->name('cities.ajax.list');

        /******************* Start Opportunities ******************************/
        Route::match(['get','post'], 'opportunities/create', 'ContactsController@createOpportunity')->name('contacts.opportunities.create');
        Route::match(['get','post'], 'opportunities/update/{id}', 'ContactsController@updateOpportunity')->name('contacts.opportunities.update');
        Route::get('opportunities', 'ContactsController@opportunities')->name('contacts.opportunities.list');
        /******************* End Opportunities ******************************/

        Route::resource('departments', 'DepartmentsController');

        Route::get('leads', 'CustomersController@leads')->name('leads.index');
        Route::get('opportunities', 'CustomersController@opportunities')->name('opportunities.index');
        Route::get('dead', 'CustomersController@dead')->name('dead.index');
        Route::get('lost', 'CustomersController@lost')->name('lost.index');
        Route::resource('customers', 'CustomersController');

        Route::resource('contacts', 'ContactsController')->except(['destroy']);
        Route::get('contacts/getContactsAjax', 'ContactsController@getContactsAjax')->name('contacts.ajax.list');

        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController')->except('show');
        Route::match(['get','post'], 'settings', 'HomeController@settings')->name('settings');
        Route::get('/', 'HomeController@index')->name('home');
    });
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable = ['title', 'status'];

    public static $rules = ['title' => 'required'];
}

app/Http/Controllers/DepartmentsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use Illuminate\Http\Request;

class DepartmentsController extends Controller
{
    protected $viewsPath = 'departments.';
    protected $data = [];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['allDepartments'] = Department::all();
        return view($this->viewsPath.'list', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = trans('departments.create');
        return view($this->viewsPath.'form', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, Department::$rules);

        $department         = new Department;
        $department->title  = $request->title;
        $department->status = $request->status;
        if($department->save()){
            return back()->with('msg', trans('common.add-success'));
        }else{
            return back()->with('msg', trans('common.add-failed'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['departmentData'] = $departmentData = Department::find($id);
        if(!$departmentData)
            return back();
        $this->data['title'] = trans('departments.update'). ': '.$departmentData->title;
        return view($this->viewsPath.'form', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, Department::$rules);

        $department         = Department::find($id);
        $department->title  = $request->title;
        $department->status = $request->status;
        if($department->save()){
            return back()->with('msg', trans('common.update-success'));
        }else{
            return back()->with('msg', trans('common.update-failed'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Department::destroy($id)){
            if(Request::ajax())
                return response(['msg' => trans('common.delete-success')], 200);
            return back()->with('msg', trans('common.delete-success'));
        }else{
            if(Request::ajax())
                return response(['msg' => trans('common.delete-failed')], 200);
            return back()->with('msg', trans('common.delete-failed'));
        }
    }
}

resources/views/departments/form.blade.php
@extends('layouts.template')

@section('title', $title)

@section('content')

    {{ (isset($departmentData)) ? Form::model($departmentData, ['url' => route('departments.update', [$departmentData->id]), 'method' => 'PUT']) : Form::open(['url' => route('departments.store')]) }}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    @if(Session::has('msg'))
                        {!! Session::get('msg') !!}
                    @endif
                    @if(!empty($errors->all()))
                        <ul class="callout callout-danger">
                            @foreach($errors->all('<li>:message</li>') as $message) {!! $message !!}  @endforeach
                        </ul>
                    @endif
                </div>
                <div class="box-body">
                    <div class="form-group col-md-12">
                        {{ Form::label('title', trans('departments.title').':') }}
                        {{ Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => trans('departments.title')]) }}
                    </div>
                    <div class="form-group col-md-12">
                        {{ Form::label('status', trans('common.status').':') }}
                        {{ Form::select('status', ['1' => trans('common.active'),'0' => trans('common.deactive')], old('status'), ['id' => 'status', 'class' => 'form-control']) }}
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    {{ Form::submit(trans('common.save'), array('class' => 'btn btn-primary')) }}
                </div>
            </div>
        </div>
    </div>
    {{ Form::close() }}

@stop

resources/views/departments/list.blade.php
@extends('layouts.template')

@section('title'){{ trans('departments.departments-list') }} @stop

@section('content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="text-right">
                <a href="{{ route('departments.create') }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-users"></i> {{ trans('common.create-new', ['item' => trans('departments.department')]) }}</a>
            </div>
            <div class="box-header">
                @if(Session::has('msg'))
                    {!! Session::get('msg') !!}
                @endif
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped text-center">
                    <thead>
                        <tr>
                            <th>{{ trans('departments.title') }}</th>
                            <th>{{ trans('common.status') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($allDepartments as $department)
                        <tr>
                            <td>{{ $department->title }}</td>
                            <td><img src="{{ asset('img/status_'.$department->status.'.png') }}" /></td>
                            <td><a href="{{ route('departments.edit', [$department->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a></td>
                            <td><button type="button" class="btn btn-danger btn-sm deleteItem" data-uid="{{$department->id}}"><i class="fa fa-trash-o" aria-hidden="true"></i></button></td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>{{ trans('departments.title') }}</th>
                            <th>{{ trans('common.status') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
</div>

@stop

@section('scripts')
    {{ Html::style('css/datatables/dataTables.bootstrap.css') }}
    {{ Html::script('js/plugins/datatables/jquery.dataTables.js') }}
    {{ Html::script('js/plugins/datatables/dataTables.bootstrap.js') }}
    <script type="text/javascript">
        $(function() {
            $("#example1").dataTable();

            $('.deleteItem').on('click', function (e) {
                e.preventDefault();
                var thisBtn = $(this);
                if(confirm('{{trans('common.delete-confirm')}}')) {
                    var url = '{{route('departments.destroy', ":id")}}';
                    $.ajax({
                        url: url.replace(':id', thisBtn.attr('data-id')),
                        type: 'DELETE',
                        contentType:'application/json',
                        headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')}
                    }).done(function () {
                        thisBtn.parents('tr').hide('slow', function(){ thisBtn.parents('tr').remove(); });
                    });
                }
            });
        });
    </script>
@stop