routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function (){

    Auth::routes();

    Route::group(['middleware' => ['auth','privileges']], function (){
        Route::get('getCitiesAjaxList/{country}/{city?}', 'Controller@getCitiesAjaxList')->name('cities.ajax.list');

        /******************* Start Opportunities ******************************/
        Route::match(['get','post'], 'opportunities/create', 'ContactsController@createOpportunity')->name('contacts.opportunities.create');
        Route::match(['get','post'], 'opportunities/update/{id}', 'ContactsController@updateOpportunity')->name('contacts.opportunities.update');
        Route::get('opportunities', 'ContactsController@opportunities')->name('contacts.opportunities.list');
        /******************* End Opportunities ******************************/

        Route::resource('departments', 'DepartmentsController');

        Route::get('leads', 'CustomersController@leads')->name('leads.index');
        Route::get('opportunities', 'CustomersController@opportunities')->name('opportunities.index');
        Route::get('dead', 'CustomersController@dead')->name('dead.index');
        Route::get('lost', 'CustomersController@lost')->name('lost.index');
        Route::resource('customers', 'CustomersController');

        Route::resource('contacts', 'ContactsController')->except(['destroy']);
        Route::get('contacts/getContactsAjax', 'ContactsController@getContactsAjax')->name('contacts.ajax.list');

        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController')->except('show');
        Route::match(['get','post'], 'settings', 'HomeController@settings')->name('settings');
        Route::get('/', 'HomeController@index')->name('home');
    });
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'parent', 'name', 'address', 'country_id', 'city_id', 'zip', 'phone', 'mobile', 'fax', 'email', 'website',
        'image', 'title', 'type', 'position', 'department', 'industry', 'employees', 'related', 'created_by', 'updated_by'
    ];

    static function rules($id='')
    {
        return [
            'name'      => 'required|max:255',
            'email'     => 'required|email|unique:contacts,email,'.$id,
            'mobile'    => 'required|unique:contacts,mobile,'.$id,
        ];
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function country()
    {
        return $this->belongsTo(Country::class);
    }

    public function parentName()
    {
        return $this->belongsTo(Contact::class, 'parent');
    }

    public function relatedName()
    {
        return $this->belongsTo(User::class, 'related');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updator()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    public function leads()
    {
        return $this->hasMany('App\Models\Customer')->whereStatus('lead');
    }

    public function opportunities()
    {
        return $this->hasMany('App\Models\Customer')->whereStatus('opportunity');
    }
}

app/Http/Controllers/ContactsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Department;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ContactsController extends Controller
{
    protected $viewsPath = 'contacts.';
    protected $data = [];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if(\Request::ajax()){
            $allContacts = Contact::latest()->skip(\Request::get('start'))->take(\Request::get('length'));
            if(\Request::has('search')){
                $allContacts->where('name', 'like', '%'.\Request::get('search')['value'].'%')
                            ->orWhere('mobile', 'like', '%'.\Request::get('search')['value'].'%')
                            ->orWhere('email', 'like', '%'.\Request::get('search')['value'].'%');
            }
            $allContacts = $allContacts->get();
            $data = [];
            if(count($allContacts)){
                foreach ($allContacts as $contact){
                    $data[] = [
                        ($contact->title && $contact->title != 'none') ? trans('contacts.titles.'.$contact->title) .' '.  $contact->name : $contact->name,
                        $contact->mobile,
                        $contact->email,
                        '<img src="'.route("image.thumbnail", ["contacts",$contact->image]).'" height="60" />',
                        trans('contacts.types.'.$contact->type),
                        '<a href="'.route("contacts.edit", [$contact->id]).'"><i class="fa fa-pencil" aria-hidden="true"></i></a>'
                    ];
                }
            }
            $this->data = [
                'data'              => $data,
                'draw'              => \Request::get('draw'),
                'recordsTotal'      => Contact::count(),
                'recordsFiltered'   => Contact::count()
            ];
            return response($this->data, 200);
        }
        return view($this->viewsPath.'list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['users'] = User::pluck('name', 'id')->all();
        $this->data['parents'] = Contact::whereParent(0)->orderBy('name', 'ASC')->pluck('name', 'id')->all();
        $this->data['title'] = trans('common.create-new', ['item' => trans('contacts.contact')]);
        return view($this->viewsPath.'form', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, Contact::rules());

        $inputs = $request->only([
            'parent', 'name', 'address', 'country_id', 'city_id', 'zip', 'phone', 'mobile', 'fax', 'email', 'website',
            'image', 'title', 'type', 'position', 'department', 'industry', 'employees', 'related'
        ]);
        if($request->hasFile('image')){
            $inputs['image'] = upload($request, 'contacts');
        }
        $inputs['created_by'] = \Auth::user()->id;
        $contact = new Contact($inputs);
        if($contact->save()){
            return back()->with('msg', trans('common.add-success'));
        }else{
            return back()->with('msg', trans('common.add-failed'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['contactData'] = Contact::findOrFail($id);
        $this->data['breadcrumb'][] = [
            'label' => trans('contacts.contacts'),
            'link'  => route('contacts.index'),
            'icon'  => 'fa-users'
        ];
        return view($this->viewsPath.'view', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['contactData'] = $contactData = Contact::findOrFail($id);

        $this->data['users'] = User::pluck('name', 'id')->all();
        $this->data['parents'] = Contact::whereParent(0)->orderBy('name', 'ASC')->pluck('name', 'id')->all();
        $this->data['title'] = trans('common.update-item', ['item' => trans('contacts.contact'). ': '. $contactData->name]);
        return view($this->viewsPath.'form', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, Contact::rules($id));

        $contact = Contact::find($id);
        $inputs = $request->only([
            'parent', 'name', 'address', 'country_id', 'city_id', 'zip', 'phone', 'mobile', 'fax', 'email', 'website',
            'image', 'title', 'type', 'position', 'department', 'industry', 'employees', 'related'
        ]);
        if($request->hasFile('image')){
            $inputs['image'] = upload($inputs['image'], 'contacts');
        }
        $inputs['updated_by'] = \Auth::user()->id;
        if($contact->update($inputs)){
            return back()->with('msg', trans('common.update-success'));
        }else{
            return back()->with('msg', trans('common.update-failed'));
        }
    }

    public function getContactsAjax()
    {
        if(\Request::has('q')){
            $contacts = Contact::select('id', 'name AS text')->where('name', 'like', '%'.\Request::get('q').'%')->orderBy('name', 'ASC')->get();
            return response($contacts, 200);
        }
    }

}

resources/views/contacts/form.blade.php
@extends('layouts.template')

@section('title', $title)

@section('content')

    {{ (isset($contactData)) ? Form::model($contactData, ['url' => route('contacts.update', [$contactData->id]), 'method' => 'PUT', 'files'=> true]) : Form::open(['url' => route('contacts.store'), 'files'=> true]) }}
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        @if(Session::has('msg'))
                            {!! Session::get('msg') !!}
                        @endif
                        @if(!empty($errors->all()))
                            <ul class="callout callout-danger">
                                @foreach($errors->all('<li>:message</li>') as $message) {!! $message !!}  @endforeach
                            </ul>
                        @endif
                    </div>
                    <div class="box-body">
                        <div class="form-group col-md-2">
                            {{ Form::label('title', trans('contacts.titles.title').':') }}
                            {{ Form::select('title', ['none' => trans('contacts.titles.none'), 'mr' => trans('contacts.titles.mr'), 'ms' => trans('contacts.titles.ms'), 'mrs' => trans('contacts.titles.mrs'), 'dr' => trans('contacts.titles.dr'), 'prof' => trans('contacts.titles.prof')], old('title'), ['id' => 'title', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-10">
                            {{ Form::label('name', trans('contacts.name').':') }}
                            {{ Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => trans('contacts.name'), 'required']) }}
                        </div>
                        <div class="form-group col-md-12">
                            {{ Form::label('address', trans('contacts.address').':') }}
                            {{ Form::text('address', old('address'), ['class' => 'form-control', 'placeholder' => trans('contacts.address')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('country', trans('countries.country-title').':') }}
                            {{ Form::select('country_id', $countries, old('country_id'), ['id' => 'country', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('city', trans('cities.city-title').':') }}
                            {{ Form::select('city_id', [], old('city_id'), ['id' => 'city', 'class' => 'form-control']) }}
                            {{ Form::hidden('currCity', old('city_id')) }}
                        </div>
                        <div class="form-group col-md-12">
                            {{ Form::label('email', trans('contacts.email').':') }}
                            {{ Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => trans('contacts.email'), 'required']) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('mobile', trans('contacts.mobile').':') }}
                            {{ Form::text('mobile', old('mobile'), ['class' => 'form-control', 'placeholder' => trans('contacts.mobile'), 'required']) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('phone', trans('contacts.phone').':') }}
                            {{ Form::text('phone', old('phone'), ['class' => 'form-control', 'placeholder' => trans('contacts.phone')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('fax', trans('contacts.fax').':') }}
                            {{ Form::text('fax', old('fax'), ['class' => 'form-control', 'placeholder' => trans('contacts.fax')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('zip', trans('contacts.zip').':') }}
                            {{ Form::text('zip', old('zip'), ['class' => 'form-control', 'placeholder' => trans('contacts.zip')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('type', trans('contacts.types.type').':') }}
                            {{ Form::select('type', ['individual' => trans('contacts.types.individual'), 'company' => trans('contacts.types.company')], old('type'), ['id' => 'type', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('parent', trans('contacts.parent').':') }}
                            {{ Form::select('parent', ['0' => 'None']+$parents, old('parent'), ['id' => 'parent', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-6 individual">
                            {{ Form::label('position', trans('contacts.position').':') }}
                            {{ Form::text('position', old('position'), ['class' => 'form-control', 'placeholder' => trans('contacts.position')]) }}
                        </div>
                        <div class="form-group col-md-6 individual">
                            {{ Form::label('department', trans('contacts.department').':') }}
                            {{ Form::text('department', old('department'), ['class' => 'form-control', 'placeholder' => trans('contacts.department')]) }}
                        </div>
                        <div class="form-group col-md-6 company">
                            {{ Form::label('industry', trans('contacts.industry').':') }}
                            {{ Form::text('industry', old('industry'), ['class' => 'form-control', 'placeholder' => trans('contacts.industry')]) }}
                        </div>
                        <div class="form-group col-md-6 company">
                            {{ Form::label('employees', trans('contacts.employees').':') }}
                            {{ Form::number('employees', old('employees'), ['class' => 'form-control', 'placeholder' => trans('contacts.employees')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('website', trans('contacts.website').':') }}
                            {{ Form::text('website', old('website'), ['class' => 'form-control', 'placeholder' => trans('contacts.website')]) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('related', trans('contacts.related').':') }}
                            {{ Form::select('related', ['0' => 'None']+$users, old('related'), ['id' => 'related', 'class' => 'form-control']) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ Form::label('image', trans('contacts.image').':') }}
                            {{ Form::file('image', array('class' => 'form-control', 'placeholder' => trans('contacts.image'))) }}
                        </div>
                        <div class="form-group col-md-6">
                            <img src="{{ (isset($contactData) && $contactData->image) ? route('image.small', ['contacts',$contactData->image]) : asset('img/no-image-found.jpg') }}" class="center-block" height="100" />
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="box-footer">
                        {{ Form::submit(trans('common.save'), array('class' => 'btn btn-primary')) }}
                    </div>
                </div>
            </div>
        </div>
    {{ Form::close() }}

@stop

@section('scripts')
    <script>
        $(document).ready(function() {
            $('.company').hide('fast');
            $('select[name="type"]').on('change', function() {
                if ($(this).val() == 'individual') {
                    $('.company').fadeOut('slow');
                    $('.individual').fadeIn('slow');
                }else if($(this).val() == 'company') {
                    $('.individual').fadeOut('slow');
                    $('.company').fadeIn('slow');
                }
            });

            var country = $('select[name="country_id"]').val();
            var currCity = $('input[name="currCity"]').val();
            getCitiesList(country, currCity);

            $('select[name="country_id"]').on('change', function () {
                country = $('select[name="country_id"]').val();
                getCitiesList(country, currCity);
            });

            function getCitiesList(country, currcity) {
                $.get('{{route('cities.ajax.list', [''])}}/'+country+'/'+currcity, function (data) {
                    $('select[name="city_id"]').html(data);
                });
            }
        });
    </script>
@stop

resources/views/contacts/list.blade.php
@extends('layouts.template')

@section('title'){{ trans('contacts.contacts') }} @stop

@section('content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="text-right">
                <a href="{{ route('contacts.create') }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-plus"></i> {{ trans('common.create-new', ['item' => trans('contacts.contact')]) }}</a>
            </div>
            <div class="box-header">
                @if(Session::has('msg'))
                    {!! Session::get('msg') !!}
                @endif
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped text-center">
                    <thead>
                        <tr>
                            <th>{{ trans('contacts.name') }}</th>
                            <th>{{ trans('contacts.mobile') }}</th>
                            <th>{{ trans('contacts.email') }}</th>
                            <th>{{ trans('contacts.image') }}</th>
                            <th>{{ trans('contacts.types.type') }}</th>
                            <th>{{ trans('common.update') }}</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>{{ trans('contacts.name') }}</th>
                            <th>{{ trans('contacts.mobile') }}</th>
                            <th>{{ trans('contacts.email') }}</th>
                            <th>{{ trans('contacts.image') }}</th>
                            <th>{{ trans('contacts.types.type') }}</th>
                            <th>{{ trans('common.update') }}</th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
</div>

@stop

@section('scripts')
{{ Html::style('css/datatables/dataTables.bootstrap.css') }}
{{ Html::script('js/plugins/datatables/jquery.dataTables.min.js') }}
{{ Html::script('js/plugins/datatables/dataTables.bootstrap.js') }}
<script type="text/javascript">
    $(function() {
        $("#example1").dataTable({
            processing: true,
            serverSide: true,
            ajax: "{{route('contacts.index')}}",
            language: {
                "emptyTable": "{{trans('common.no-data-found')}}"
            }
        });
    });
</script>
@stop

resources/views/contacts/view.blade.php
@extends('layouts.template')

@section('title', trans('contacts.contact'))

@section('content')
    <section class="content invoice">
        <!-- title row -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-user"></i> {{ ($contactData->title && $contactData->title != 'none') ? trans('contacts.titles.'.$contactData->title) .' '.  $contactData->name : $contactData->name }}
                    <span class="text-muted">( {{ trans('contacts.types.'.$contactData->type) }} )</span>
                    <small class="pull-right">Date: {{ $contactData->created_at }}</small>
                </h2>
            </div><!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-6 invoice-col">
                <address>
                    {{ $contactData->address }}<br/>
                    {{  @$contactData->city->name . ', ' . @$contactData->country->name }}<br>
                    <strong>{{ trans('contacts.zip') }}:</strong> {{ $contactData->zip }}<br/>
                    <strong>{{ trans('contacts.mobile') }}:</strong> {{ $contactData->mobile }}<br/>
                    <strong>{{ trans('contacts.phone') }}:</strong> {{ $contactData->phone }}<br/>
                    <strong>{{ trans('contacts.fax') }}:</strong> {{ $contactData->fax }}<br/>
                    <strong>{{ trans('contacts.email') }}:</strong> {{ $contactData->email }}
                </address>
            </div><!-- /.col -->
            <div class="col-sm-6 invoice-col">
                <address>
                    @if($contactData->type == 'individual')
                        <strong>{{ trans('contacts.position') }}:</strong> {{ $contactData->position }}<br>
                        <strong>{{ trans('contacts.department') }}:</strong> {{ $contactData->department }}<br>
                    @else
                        <strong>{{ trans('contacts.industry') }}:</strong> {{ $contactData->industry }}<br>
                        <strong>{{ trans('contacts.employees') }}:</strong> {{ $contactData->employees }}<br>
                    @endif
                    <strong>{{ trans('contacts.child-of') }}:</strong> <a href="{{route('contacts.show', [@$contactData->parentName->id])}}" target="_blank">{{ @$contactData->parentName->name }}</a><br>
                    <strong>{{ trans('contacts.related') }}:</strong> {{ @$contactData->relatedName->name }}<br>
                    <strong>{{ trans('contacts.created-by') }}:</strong> {{ @$contactData->creator->name }}<br>
                    <strong>{{ trans('contacts.updated-by') }}:</strong> {{ @$contactData->updator->name }}<br>
                </address>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
@stop