routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function (){

    Auth::routes();

    Route::group(['middleware' => ['auth','privileges']], function (){
        Route::get('getCitiesAjaxList/{country}/{city?}', 'Controller@getCitiesAjaxList')->name('cities.ajax.list');

        /******************* Start Opportunities ******************************/
        Route::match(['get','post'], 'opportunities/create', 'ContactsController@createOpportunity')->name('contacts.opportunities.create');
        Route::match(['get','post'], 'opportunities/update/{id}', 'ContactsController@updateOpportunity')->name('contacts.opportunities.update');
        Route::get('opportunities', 'ContactsController@opportunities')->name('contacts.opportunities.list');
        /******************* End Opportunities ******************************/

        Route::resource('departments', 'DepartmentsController');

        Route::get('leads', 'CustomersController@leads')->name('leads.index');
        Route::get('opportunities', 'CustomersController@opportunities')->name('opportunities.index');
        Route::get('dead', 'CustomersController@dead')->name('dead.index');
        Route::get('lost', 'CustomersController@lost')->name('lost.index');
        Route::resource('customers', 'CustomersController');

        Route::resource('contacts', 'ContactsController')->except(['destroy']);
        Route::get('contacts/getContactsAjax', 'ContactsController@getContactsAjax')->name('contacts.ajax.list');

        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController')->except('show');
        Route::match(['get','post'], 'settings', 'HomeController@settings')->name('settings');
        Route::get('/', 'HomeController@index')->name('home');
    });
});

resources/views/layouts/partials/_cities.blade.php
@if(isset($cities) && count($cities))
    <option value="0">{{ trans('cities.select-city') }}</option>
    @foreach($cities as $city)
        <option value="{{$city->id}}" @if($currCity == $city->id) selected="selected" @endif>{{ $city->name }}</option>
    @endforeach
@else
    <option value="0" disabled="disabled">{{ trans('countries.select-country') }}</option>
@endif

resources/views/layouts/partials/_head.blade.php
<head>
    <title>{{ @$config->site_name }} :: @yield('title')</title>

    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- bootstrap 3.0.2 -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}" />
    <!-- font Awesome -->
    <link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('css/ionicons.min.css') }}" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('css/AdminLTE.css') }}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @yield('styles')
</head>

resources/views/layouts/partials/_header.blade.php
<!-- header logo: style can be found in header.less -->
<header class="header">
    <a href="{{ route('home') }}" class="logo">{{ @$config->site_name }}</a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i>
                        <span>{{ Auth::user()->name }} <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            <img src="{{ asset('img/avatar3.png') }}" class="img-circle" alt="User Image" />
                            <p>{{ Auth::user()->name }}<small> {{ Auth::user()->created_at }}</small></p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ route('users.edit', Auth::user()->id) }}" class="btn btn-default btn-flat">{{ trans('users.profile') }}</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">{{ trans('users.signup') }}</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/partials/_sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('img/avatar3.png') }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Hello, {{ str_limit(Auth::user()->name, 10) }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <?php $direction = (\App::getLocale() == 'ar') ? 'left' : 'right'; ?>
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li @if(Request::is('home')) class="active" @endif><a href="{{ route('home') }}" ><i class="fa fa-dashboard"></i> <span>{{ trans('common.cpanel') }}</span></a></li>
            <li @if(Request::is('settings')) class="active" @endif><a href="{{ route('settings') }}"><i class="fa fa-cogs"></i><span>{{ trans('settings.settings') }}</span></a></li>
            <li class="treeview @if(Request::is('contacts', 'contacts/*', 'customers', 'customers/*', 'leads', 'opportunities', 'dead', 'lost')) active @endif">
                <a href="#"><i class="fa fa-users"></i><span>{{ trans('contacts.contacts') }}</span><i class="fa fa-angle-{{$direction}} pull-right"></i></a>
                <ul class="treeview-menu">
                    <li @if(Request::is('contacts', 'contacts/*')) class="active" @endif><a href="{{ route('contacts.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.contacts') }}</a></li>
                    <li @if(Request::is('leads')) class="active" @endif><a href="{{ route('leads.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.leads') }}</a></li>
                    <li @if(Request::is('opportunities')) class="active" @endif><a href="{{ route('opportunities.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.opportunities') }}</a></li>
                    <li @if(Request::is('dead')) class="active" @endif><a href="{{ route('dead.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.dead') }}</a></li>
                    <li @if(Request::is('lost')) class="active" @endif><a href="{{ route('lost.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.lost') }}</a></li>
                    <li @if(Request::is('customers', 'customers/*')) class="active" @endif><a href="{{ route('customers.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('contacts.view.customers') }}</a></li>
                </ul>
            </li>
            <li class="treeview @if(Request::is('users', 'users/*', 'departments', 'departments/*', 'roles', 'roles/*')) active @endif">
                <a href="#"><i class="fa fa-users"></i><span>{{ trans('users.users') }}</span><i class="fa fa-angle-{{$direction}} pull-right"></i></a>
                <ul class="treeview-menu">
                    <li @if(Request::is('users/create')) class="active" @endif><a href="{{ route('users.create') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('users.create') }}</a></li>
                    <li @if(Request::is('users', 'users/*')) class="active" @endif><a href="{{ route('users.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('users.view-users') }}</a></li>
                    <li @if(Request::is('roles', 'roles/*')) class="active" @endif><a href="{{ route('roles.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('roles.view-roles') }}</a></li>
                    <li @if(Request::is('departments', 'departments/*')) class="active" @endif><a href="{{ route('departments.index') }}"><i class="fa fa-angle-double-{{$direction}}"></i> {{ trans('departments.view-departments') }}</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" ><i class="fa fa-sign-out"></i> <span>{{ trans('users.logout') }}</span></a>
                {{ Form::open(['url' => route('logout'), 'method' => 'POST', 'id' => 'logout-form', 'class' => 'hide']) }}{{ Form::close() }}
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>