routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(array('prefix' => 'image/{dir}/'), function() {
    Route::get('{filename}', 'Controller@getImage')->name('image');
    Route::get('large-{filename}', 'Controller@getImage')->name('image.large');
    Route::get('medium-{filename}', 'Controller@getImage')->name('image.medium');
    Route::get('small-{filename}', 'Controller@getImage')->name('image.small');
    Route::get('thumbnail-{filename}', 'Controller@getImage')->name('image.thumbnail');
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function (){

    Auth::routes();

    Route::group(['middleware' => ['auth','privileges']], function (){
        Route::get('getCitiesAjaxList/{country}/{city?}', 'Controller@getCitiesAjaxList')->name('cities.ajax.list');

        /******************* Start Opportunities ******************************/
        Route::match(['get','post'], 'opportunities/create', 'ContactsController@createOpportunity')->name('contacts.opportunities.create');
        Route::match(['get','post'], 'opportunities/update/{id}', 'ContactsController@updateOpportunity')->name('contacts.opportunities.update');
        Route::get('opportunities', 'ContactsController@opportunities')->name('contacts.opportunities.list');
        /******************* End Opportunities ******************************/

        Route::resource('departments', 'DepartmentsController');

        Route::get('leads', 'CustomersController@leads')->name('leads.index');
        Route::get('opportunities', 'CustomersController@opportunities')->name('opportunities.index');
        Route::get('dead', 'CustomersController@dead')->name('dead.index');
        Route::get('lost', 'CustomersController@lost')->name('lost.index');
        Route::resource('customers', 'CustomersController');

        Route::resource('contacts', 'ContactsController')->except(['destroy']);
        Route::get('contacts/getContactsAjax', 'ContactsController@getContactsAjax')->name('contacts.ajax.list');

        Route::resource('users', 'UsersController');
        Route::resource('roles', 'RolesController')->except('show');
        Route::match(['get','post'], 'settings', 'HomeController@settings')->name('settings');
        Route::get('/', 'HomeController@index')->name('home');
    });
});

resources/views/roles/form.blade.php
@extends('layouts.template')

@section('title', $title)

@section('content')

    {{ (isset($roleData)) ? Form::model($roleData, ['url' => route('roles.update', [$roleData->id]), 'method' => 'PUT']) : Form::open(['url' => route('roles.store')]) }}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    @if(Session::has('msg'))
                        {!! Session::get('msg') !!}
                    @endif
                    @if(!empty($errors->all()))
                        <ul class="callout callout-danger">
                            @foreach($errors->all('<li>:message</li>') as $message) {!! $message !!}  @endforeach
                        </ul>
                    @endif
                </div>
                <div class="box-body">
                    <div class="form-group col-md-12">
                        {{ Form::label('name', trans('roles.name').':') }}
                        {{ Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => trans('roles.name')]) }}
                    </div>
                    <div class="form-group col-md-12">
                        {{ Form::label('description', trans('roles.description').':') }}
                        {{ Form::textarea('description', old('description'), ['id' => 'description', 'class' => 'form-control', 'placeholder' => trans('roles.description'), 'rows' => '3']) }}
                    </div>
                    <div class="form-group col-md-12">
                        {{ Form::label('permissions', trans('roles.privileges').':') }}
                        <?php /*<table class="table table-bordered text-center">
                            <tr>
                                <th>{{trans('roles.actions.action')}}</th>
                                <th>{{trans('roles.actions.view')}}</th>
                                <th>{{trans('roles.actions.new')}}</th>
                                <th>{{trans('roles.actions.edit')}}</th>
                                <th>{{trans('roles.actions.destroy')}}</th>
                            </tr>
                            @foreach(config('privileges') as $name=>$privilage)
                                <tr>
                                    <td>{{ trans($name) }}</td>
                                    <td>@if(in_array('view', $privilage)){{ Form::checkbox('view[]', substr(strrchr($name, '.'), 1), (is_array(json_decode($roleData->view)) && in_array(substr(strrchr($name, '.'), 1), json_decode($roleData->view)))) }}@endif</td>
                                    <td>@if(in_array('new', $privilage)){{ Form::checkbox('new[]', substr(strrchr($name, '.'), 1), (is_array(json_decode($roleData->new)) && in_array(substr(strrchr($name, '.'), 1), json_decode($roleData->new)))) }}@endif</td>
                                    <td>@if(in_array('edit', $privilage)){{ Form::checkbox('edit[]', substr(strrchr($name, '.'), 1), (is_array(json_decode($roleData->edit)) && in_array(substr(strrchr($name, '.'), 1), json_decode($roleData->edit)))) }}@endif</td>
                                    <td>@if(in_array('destroy', $privilage)){{ Form::checkbox('destroy[]', substr(strrchr($name, '.'), 1), (is_array(json_decode($roleData->destroy)) && in_array(substr(strrchr($name, '.'), 1), json_decode($roleData->destroy)))) }}@endif</td>
                                </tr>
                            @endforeach
                        </table>
                        <hr/>*/?>
                        <table class="table table-bordered text-center">
                            <tr>
                                <th>{{trans('roles.actions.action')}}</th>
                                <th>None</th>
                                <th>Read Only</th>
                                <th>Read & Write</th>
                            </tr>
                            @foreach(config('privileges') as $name)
                                <tr>
                                    <td>{{ trans($name) }}</td>
                                    <td>{{ Form::radio(substr(strrchr($name, '.'), 1), '0', ($roleData->privilegesDecoded(substr(strrchr($name, '.'), 1)) == '0') ) }}</td>
                                    <td>{{ Form::radio(substr(strrchr($name, '.'), 1), '1', ($roleData->privilegesDecoded(substr(strrchr($name, '.'), 1)) == '1') ) }}</td>
                                    <td>{{ Form::radio(substr(strrchr($name, '.'), 1), '2', ($roleData->privilegesDecoded(substr(strrchr($name, '.'), 1)) == '2') ) }}</td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="box-footer">
                    {{ Form::submit(trans('common.save'), array('class' => 'btn btn-primary')) }}
                </div>
            </div>
        </div>
    </div>
    {{ Form::close() }}

@stop

resources/views/roles/list.blade.php
@extends('layouts.template')

@section('title'){{ trans('roles.roles-list') }} @stop

@section('content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="text-right">
                <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-key"></i> {{ trans('common.create-new', ['item' => trans('roles.role')]) }}</a>
            </div>
            <div class="box-header">
                @if(Session::has('msg'))
                    {!! Session::get('msg') !!}
                @endif
            </div><!-- /.box-header -->
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped text-center">
                    <thead>
                        <tr>
                            <th>{{ trans('roles.name') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($allRoles as $role)
                        <tr>
                            <td>{{ $role->name }}</td>
                            <td><a href="{{ route('roles.edit', [$role->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a></td>
                            <td>@if($role->id > 1)<button type="button" class="btn btn-danger btn-sm deleteItem" data-id="{{$role->id}}"><i class="fa fa-trash-o" aria-hidden="true"></i></button>@endif</td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>{{ trans('roles.name') }}</th>
                            <th>{{ trans('common.update') }}</th>
                            <th>{{ trans('common.delete') }}</th>
                        </tr>
                    </tfoot>
                </table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
</div>

@stop

@section('scripts')
    {{ Html::style('css/datatables/dataTables.bootstrap.css') }}
    {{ Html::script('js/plugins/datatables/jquery.dataTables.js') }}
    {{ Html::script('js/plugins/datatables/dataTables.bootstrap.js') }}
    <script type="text/javascript">
        $(function() {
            $("#example1").dataTable();

            var url = '{{route('roles.destroy', ":id")}}';
            $('.deleteItem').on('click', function (e) {
                e.preventDefault();
                var thisBtn = $(this);
                if(confirm('{{trans('common.delete-confirm')}}')) {
                    $.ajax({
                        url: url.replace(':id', thisBtn.attr('data-id')),
                        type: 'DELETE',
                        contentType:'application/json',
                        headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')}
                    }).done(function () {
                        thisBtn.parents('tr').hide('slow', function(){ thisBtn.parents('tr').remove(); });
                    });
                }
            });
        });
    </script>
@stop